export const FETCH_DEPARTMENT = 'FETCH_DEPARTMENT';
export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT';
 
export const FETCH_EMPLOYEE = 'FETCH_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
 
export const FETCH_SALARY = 'FETCH_SALARY';
export const ADD_SALARY = 'ADD_SALARY';
export const UPDATE_SALARY = 'UPDATE_SALARY';
export const DELETE_SALARY = 'DELETE_SALARY';

export const SALARY_RANGE_SEARCH = 'SALARY_RANGE_SEARCH';
export const SALARY_SEARCH_BY_DEPARTMENT = 'SALARY_SEARCH_BY_DEPARTMENT';
export const EMPLOYEE_SEARCH = 'EMPLOYEE_SEARCH';


export const ADD_REGISTRATION = 'ADD_REGISTRATION';